services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: noorbatool
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://db:27017/focusflow
      - NODE_ENV=production
    depends_on:
      - db
    restart: always

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: always
volumes:
  db_data:
