version: '3.8'

services:
  focusflow-app:
    image: node:20-alpine
    container_name: focusflow2-ci
    working_dir: /app
    volumes:
      - .:/app 
    ports:
      - "4000:3000" 
    environment:
      - MONGODB_URI=mongodb://noor:noor123@cluster0-shard-00-00.ylkll.mongodb.net:27017,cluster0-shard-00-01.ylkll.mongodb.net:27017,cluster0-shard-00-02.ylkll.mongodb.net:27017/?ssl=true&replicaSet=atlas-le2i56-shard-0&authSource=admin&appName=Cluster0
      - NODE_ENV=development 
    command: >
      sh -c "npm install @tailwindcss/postcss postcss && npm install && npm run dev -- -p 3000"
