apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: focusflow-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focusflow-db
  template:
    metadata:
      labels:
        app: focusflow-db
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
