apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: focusflow-db
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017
  selector:
    app: focusflow-db
