apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: focusflow-web
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: focusflow-web
